const blog = [
  {
    id: 'ad66f23b-b031-4cbd-aa72-9e528b52261e',
    title: 'Xbox laat gebruikers toetsenbordkeys remappen op Elite 2- en Adaptive-controller',
    synopsis: 'Microsoft voegt een optie toe om toetsenbordtoetsen te binden op de Xbox Elite Series 2- en Xbox Adaptive-controllers. Daarmee kunnen gebruikers gemakkelijker pc-games met beperkte controllerondersteuning spelen.',
    content: '<p>De keybindfeature kwam in augustus al <a href="https://tweakers.net/nieuws/212388/xbox-accessoires-app-krijgt-remapping-tool-voor-elite-2-en-adaptive-controller.html">beschikbaar voor Xbox Insiders</a>, maar is in <a href="https://news.xbox.com/en-us/2023/10/26/xbox-october-update-2023/" rel="external noopener" target="_blank">de recentste Xbox-update beschikbaar gesteld</a> voor alle gebruikers. De functie werkt via de Xbox Accessories-app op zowel consoles als de pc. Gebruikers kunnen hiermee toetsenbordknoppen naar keuze instellen op alle knoppen van hun Elite Series 2- of Adaptive-controller.</p><p>Het is ook mogelijk om toetsencombinaties, zoals <code>Ctrl + Shift + C</code>, in te stellen op een enkele controllerknop. Het is niet mogelijk om meerdere <em>non-modifiers</em> in te stellen. De toetsencombinatie <code>Ctrl + Shift + C + V</code> zou bijvoorbeeld niet werken. Microsoft publiceerde eerder <a href="https://news.xbox.com/en-us/2023/08/03/keyboard-button-mapping-for-xbox-controllers/" rel="external noopener" target="_blank">een blogpost met uitleg</a> over de feature.</p><p>In de update voegt Microsoft ook een optie toe om Xbox-gamecaptures gemakkelijk te importeren naar Microsoft Clipchamp, de ingebouwde videobewerkingssoftware voor Windows. Gebruikers kunnen de video\'s daarmee bewerken en delen. Verder wordt het makkelijker voor Xbox-gebruikers om dataverzameling uit te zetten. Wanneer gebruikers die optie op één apparaat uitzetten, wordt dat automatisch toegepast op alle apparaten die gekoppeld zijn aan het account van de gebruiker.</p><div class="alignCenter"><figure class="image"><a data-highres-src="https://tweakers.net/ext/i/2006194752.jpeg" href="https://tweakers.net/i/iZrTXSsix2csDFVzixjKwJW1cSs=/1280x/filters:strip_icc():strip_exif()/i/2006194752.jpeg?f=imagegallery" rel="imageviewer"><img alt="Xbox Keyboard-mapping" class="border" height="369" data-src="https://tweakers.net/i/-DTiouiwuj36q32-Krsiub171tQ=/656x/filters:strip_icc():strip_exif()/i/2006194752.jpeg?f=imagenormal" width="656" src="https://tweakers.net/i/-DTiouiwuj36q32-Krsiub171tQ=/656x/filters:strip_icc():strip_exif()/i/2006194752.jpeg?f=imagenormal" data-lazyload="1"></a><figcaption>Bron: Xbox</figcaption></figure></div>',
    category: 'Nieuws',
    pubDate: 1698402420000,
  },
  {
    id: '6b3b15d3-5741-4290-8a90-95ab3f9ea267',
    title: '\'Google betaalde 18 miljard dollar voor zoekmachinedeal met Apple in 2021\'',
    synopsis: 'Google heeft Apple in 2021 18 miljard dollar betaald om de standaardzoekmachine in Safari te zijn. Dat melden ingewijden aan The New York Times. De zoekmachinedeal tussen Google en Apple kwam onlangs in opspraak wegens een Amerikaanse antitrustzaak rondom Google Search',
    content: '<p>Twee anonieme bronnen <a href="https://www.nytimes.com/2023/10/26/technology/google-apple-search-spotlight.html?partner=slack&amp;smid=sl-share" rel="external noopener" title="Inside Google’s Plan to Stop Apple From Getting Serious About Search - The New York Times" target="_blank">vertellen aan The New York Times</a> dat Google 18 miljard dollar heeft betaald om de standaardzoekmachine te blijven in Apples Safari-webbrowser. Het bedrijf deed dat specifiek in 2021; het is niet bekend of de techgigant in andere jaren hetzelfde bedrag aan Apple betaalde. Er was tot op heden nog geen concreet bedrag bekend dat Google aan Apple heeft betaald. De twee bedrijven hebben het bedrag van 18 miljard dollar ook nog niet officieel bevestigd.</p>',
    category: 'Nieuws',
    pubDate: 1698402420000,
  }
];